export const VOUCHER_SHOW_LIST = "VOUCHER_SHOW_LIST"
export const VOUCHER_SAVE = "VOUCHER_SAVE"
export const VOUCHER_ADD = "VOUCHER_ADD"
export const VOUCHER_ADD_DETAIL = "VOUCHER_ADD_DETAIL"
export const VOUCHER_SAVE_DETAIL = "VOUCHER_SAVE_DETAIL"

export const ACCOUNT_ADD = "ACCOUNT_ADD"
export const ACCOUNT_SAVE = "ACCOUNT_SAVE"
export const ACCOUNT_CANCEL = "ACCOUNT_CANCEL"
